### ISSUE TITLE
.suo, .user, bin, obj should not be commited to Git

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#1]
Files `.suo` and `.user`, folders `bin`, `obj` should not be commited to Git.

See: http://stackoverflow.com/questions/72298/should-i-add-the-visual-studio-suo-and-user-files-to-source-control

You may use the .gitignore file, which is used in all StarcounterSamples: https://github.com/StarcounterSamples/Polyjuice/wiki/.gitignore

**Comment by jakubklekota** [comment]
fixed

**Comment by warpech** [comment]
Thanks
