### ISSUE TITLE
Add support for subscription payments

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#16]
@miyconst will have more information about what is the requirement

**Comment by miyconst** [comment]
I am a bit lost, what this issue suppose to fix?

**Comment by warpech** [comment]
We discussed last week that your customer needs subscription (recurring) payments by credit card. If this is still on table then perhaps you have some requirements.

Otherwise we still need such functionality, but then I @jakubklekota should define how this will work based on what's available in the payment provider API.

**Comment by miyconst** [comment]
That is correct. Any SAAS system requires subscription payments, but I thought it should be done in the system itself. A Subscription is a Payable, subscription with different options/terms are different payables with different prices.

Payment app should not care about it, it just provides functionality to pay for a payable. Am I missing something?

----

The other feature is interval payments. For example GitHub cuts some amount of money from my account each month. Is this what you meant?

**Comment by warpech** [comment]
> Payment app should not care about it, it just provides functionality to pay for a payable. Am I missing something?

Let's see what @jakubklekota has to say about it. Actually I don't even know if the recurring payment (let's say each month) is done automatically by Braintree or does it need to be triggered by app. 

When I am subscribed to a service, a Starcounter app should display all past monthly payments for a user (not only the subscription order) as well as allow upgrading/degrating/cancelling of the subscriptions.

**Comment by jakubklekota** [comment]
Hi @warpech @miyconst,

Generally in BrainTree API we can defined recurring payment (create, modify), so in the BrainTree app, we can add custom view, to creating recurring payment by user.

@warpech - I agree with you

>When I am subscribed to a service, a Starcounter app should display all past monthly payments for a user (not only the subscription order) as well as allow upgrading/degrating/cancelling of the subscriptions.

@miyconst 
> Payment app should not care about it, it just provides functionality to pay for a payable.

I think, should be. Why ? Basically... I'm a user, and i don't know who is payment provider. If payment app should not care about it, for each user we have create new account in BrainTree as  payment provider - for managment his payments, which seems illogical.

If we provide BrainTree app as completly app, each user have access to his payment via app, not via payment provider.

**Comment by warpech** [comment]
We just discussed with @miyconst that the data model for this feature needs to be aligned with the data model of Society Objects. Need to ask @Starcounter-Jack about it. Let's put this issue on hold for at least a week.

**Comment by warpech** [comment]
We discussed with @Starcounter-Jack. This will be made in form of another app storing the card number information and creating `Payable` object once a month. Braintree app will then execute each payment, treating it the same as a single payment.

**Comment by warpech** [comment]
Closing as out of scope
