### ISSUE TITLE
Packages directory should not be submitted to git

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#28]
I think that packages directory should not be submitted to git. Now it is. @aloscha WDYT?

**Comment by aloscha** [comment]
Agree, but I've add it because of bower lose problems. For me personally it could be removed.

**Comment by warpech** [comment]
`Packages` directory comes from nuget, not bower.

**Comment by aloscha** [comment]
I know :), it's should be removed

**Comment by warpech** [comment]
Thx, I will do it

**Comment by warpech** [comment]
Also this file should be removed: `.vs/config/applicationhost.config`

**Comment by warpech** [comment]
Implemented in #29, waiting for review

**Comment by aloscha** [comment]
Reviewed and closed.
