### ISSUE TITLE
All handlers must start with the app name

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#4]
As noted by @miyconst:

All URLs handled by an app must use the app name as the first segment in the URL. Otherwise it will fail the check performed by: [`EnforceURINamespaces` sanitization flag](http://starcounter.io/guides/database/database-configuration/)

In case of the Braintree app, the URLs need to begin with `/braintree`.

I noticed this is not documented anywhere. I added an issue about that: https://github.com/Starcounter/starcounter.io/issues/84

**Comment by jakubklekota** [comment]
fixed
