### ISSUE TITLE
All files in wwwroot need to be moved to wwwroot/braintree

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#5]
Otherwise some other app could potentially overwrite the response.

I noticed it is not documented, so I've added an issue: https://github.com/Starcounter/starcounter.io/issues/85

**Comment by miyconst** [comment]
Just to note, the correct folder name should be `wwwroot/Braintree` where `Braintree` should be exactly the same as application name, including case of letters.

**Comment by jakubklekota** [comment]
@warpech @miyconst . I know, but I suggested the another solution, beacuse the structure file for every app is not the same, and for new app we have to creating the same const file.
So, when we create the new app, we can get another project and then remove only the folder name associated with the application name, and we have blank app with const file which must include for every app. I think this solution can save time for everyone who can create app.

It's no better ?

**Comment by miyconst** [comment]
Sorry, @jakubklekota, I got lost in your idea. Could you provide an example of what you mean?

**Comment by jakubklekota** [comment]
@miyconst - an example for BraintreeDemoApp:
 
When we delete the following:
Api/BrainTreePayment - this folder and all files
ViewModels - all folders without Partials and RootPage.json
wwwroot - all folders

As the result of the above we get this structure:
 
Solution
-- Api
--- MainHandlers.cs
 
-- ViewModels
--- Partials
--- RootPage.json
 
--wwroot
---AppIconPage.html
---LauncherWrapperPage.html
---RootPage.html
---AppName.json

What I'm suggesting here is to create a blank app (which can be used as a starting point in building another app) by removing all the files and folders named after (or associated with) the name of the current application. What's left can be reused then as a blank template.

**Comment by miyconst** [comment]
So, your idea is to use `LauncherWrapperPage.html` and some other files from different applications at the same time. Am I correct?

The idea is good, but the proposed solution is not. This is why:

1. Applications should not depend on each other.
2. Some other application, which is unaware of such behavior could replace the files with it's own and break down entire set of applications.

We have in plans to add those files into Starcounter itself, so you will have to create them only if default ones do not fit you.

**Comment by warpech** [comment]
Thanks for the idea, we are looking into ways to simplify creating new projects so that zero boilerplate will be needed (see https://github.com/starcountersamples/barcodes2/issues).

The problem is that if you have two apps running, and both of them register:

```
--wwwroot
----AppIconPage.html
```

The first one will be overwritten and the last one will win as `http://localhost:8080/AppIconPage.html`.

This is why all static files in wwwroot directory need to be namespaced with a subdirectory named as the application.

**Comment by jakubklekota** [comment]
@miyconst Yes, you are :+1: 

@warpech thanks.

**Comment by jakubklekota** [comment]
fixed
