### ISSUE TITLE
Public methods should never use Tuple

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/Braintree#8]
`Tuple` should never be used in public methods available for third party developers, unless you really want to prevent people from using your code.

Incorrect `Tuple` usage was found here: https://github.com/handsoncode-apps/BraintreeDemoApp/blob/master/BrainTreeApi/Services/CustomerService/Customer.cs#L31

Read more about Tuples here:
http://stackoverflow.com/questions/3017352/is-using-net-4-0-tuples-in-my-c-sharp-code-a-poor-design-decision
And here:
http://stackoverflow.com/questions/7197579/what-tuples-are-good-for
And here:
http://blogs.msdn.com/b/sajoshi/archive/2011/05/22/practical-usage-of-tuple-in-c.aspx

**Comment by jakubklekota** [comment]
fixed
