### ISSUE TITLE
Payment applications should save history of transactions

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/Braintree#9]

**Comment by warpech** [comment]
Good point, but let's make it a separate app. I would give it a working title "TransactionsReport".

Braintree app should just create the `Transaction`, submit it to the gateway, and update the current state of that transaction in Starcounter db.

@miyconst, @jakubklekota WDYT?

**Comment by miyconst** [comment]
@warpech, probably you misunderstood me. For safety and debugging reasons Braintree application should save all transactions it sends to gateway and responses.

If we have another app "TransactionsReport" then we have to teach it to log transactions of all payment methods, which is not good.

**Comment by warpech** [comment]
Ok, then this issue is exactly the same as my #11?

**Comment by jakubklekota** [comment]
@miyconst do you mean store raw (like xml) request and response ?

**Comment by miyconst** [comment]
Both, raw (xml, json) and parameters should be saved.

Let's say you have a bug in serialiser, then it would be much easier to catch, if you have parameter values and request body logged.

**Comment by jakubklekota** [comment]
@miyconst I know what do you mean and agree with you.

**Comment by warpech** [comment]
@miyconst so then actually I misunderstood you once again. Now I get the point.

But do you think this API request/response log should be saved in the db? I think it should be saved in the event/error log: http://starcounter.io/guides/tools/error-log/

**Comment by miyconst** [comment]
I prefer to save it in database. There is no that much of data, and in future there should be a back-end which is available for admin only, which displays history of the requests.

The request body could be saved into files, but the transaction details should be saved to database.

**Comment by jakubklekota** [comment]
fixed
